# Stages of pipeline, should match with stage tag inside each job.
# Each stages executes in sequence, if previous job fails, then all the preceeding jobs are skipped.
stages:
  - mavenbuild
  - maventest
  - springdeploy

maven-build-prod:
  stage: mavenbuild
  tags:
    - spring_runner
  script:
    - cd Backend/MyClub
    - mvn package -B
  only:
    refs:
      - master
    changes:
      - Backend/**/*
    

maven-test-prod:
  stage: maventest
  tags:
    - spring_runner
  script:
    - cd Backend/MyClub
    - mvn test
  artifacts:
    paths:
      - Backend/MyClub/target/*.jar
  only:
    refs:
      - master
    changes:
      - Backend/**/*
      
spring-deploy-prod:
  stage: springdeploy
  tags:
   - spring_runner
  script:
    - cd Backend/MyClub
    - mvn package
    - sudo mv target/api.jar /backend/web-demo.jar
    - sudo systemctl stop system-web-demo
    - sudo systemctl start system-web-demo
  only:
    refs:
      - master
    changes:
      - Backend/**/*
